apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-assignment-app-pipeline-run-
spec:
  params:
    - name: source-repo
      value: https://github.com/nickmerrett/buildah-assignment
    - name: image-repo
      value:  quay.io/nickmerrett/buildah-assignment
    - name: app-name
      value: buildah-assignment
    - name: app-namespace
      value: nick-merrett-pipeline-from-scratch
    - name: commit
      value: ""
  serviceAccountName: build-bot
  pipelineRef:
    name: buildah-assignment-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
