apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app: buildah-assignment
  app.kubernetes.io/instance: buildah-assignment-app-instance
  app.kubernetes.io/name: buildah-assignment-app

images:
  - name: quay.io/jeffdean/buildah-assignment
    newName: quay.io/nickmerrett/buildah-assignment

